### ISSUE TITLE
Query: 0.5 compatibility

### ISSUE THREAD

**Issue by drewsmith-uk** [cptjhmiller/OMV_Installers#6]
Is this installer compatible with v0.5 of OMV?

Or to put it another way, in theory is there any reason why the installed software shouldn't work?

Apologies but it's not worth my time to upgrade to 0.5 just to find out, yet I do use many of the listed apps in my current installation (0.4) thanks to your script.

**Comment by cptjhmiller** [comment]
Most apps still work under 0.5. I you can type clean in the script and it will make the plugins ready for the upgrade, but I would suggest a clean install as I have not check the clean section for a while, it should work but can't say for sure.

**Comment by drewsmith-uk** [comment]
Thanks, so your advice is remove, then upgrade and reinstall rather than try to keep them through the upgrade?

**Comment by cptjhmiller** [comment]
My advise would be, in order,
1. Wait for omv 0.6 as most apps will be converted to proper plugins
2. remove apps using script (this clears side menu items) update to 0.5 and install plugins or use script to install
3. run script and type clean, this converts the side menu items to work with omv 0.5

It is the side menu item that cause problems when going from 0.4 - 0.5 if you have no side menu items then you can just upgrade.

**Comment by drewsmith-uk** [comment]
Regarding your point (1), are you suggesting always staying a 0.1 version behind the latest to ensure plugins are available? i.e. when 0.6 is out I shouldn't jump to 0.6?

Feel free to close this issue after replying, thanks for your help.

**Comment by cptjhmiller** [comment]
The next version of OMV  (0.6 or 1.0 not sure what it will be) will be based on wheezy so will have latest version of software (python2.7 php ect.) so I would go from 0.4 to 0.6 and skip 0.5. You are running 0.4 now and you are not having issues then I would keep it and then upgrade to the wheezy version when its released.

The plugin devs have started working on the plugins for this new version so when it is released the plugins should be available, this was not true of other OMV version.

If you say what apps you have installed I can check if there is a plugin ready for it.

**Comment by drewsmith-uk** [comment]
Ah OK I get you now.

I wanted to upgrade to the latest OMV version but can definitely hang on for 0.6 as from what you've said it sounds like waiting will be worthwhile.

I mainly use my OMV server for SAB/Sickbeard/CouchPotatoServer installed via your script as well as PlexMediaServer.

**Comment by cptjhmiller** [comment]
I personally would hold on as well, I also would use the plugin version of those apps as they are ready in omv 0.5 and should be ready when the wheezy version is released. The plugin version of SAB can be updated via the plugin page as well so no need to manually update like with the script version.
